### ISSUE TITLE
需要同步一份术语的词汇表翻译

### ISSUE THREAD

**Issue by einverne** [BeanMr/apache-kafka-documentation-cn#3]
目前翻译第四章时遇到些问题，有必要同步一下一些术语的翻译，目前 kafka 还在学习阶段，所以翻译难免有些生硬，见谅

- Replicated Logs  还有 replicas
- Pipeline  翻译成 管线 似乎总有些绕口
- In-Sync Replicas

**Comment by BeanMr** [comment]
的确术语不同步是个严重的问题，我在后续校对中注意的。如果您正在翻译您可以直接提交PRs大家一起在具体的语境讨论。

* Replicated Logs最多的情况是表示 **副本记录** replicas表示 **副本**
* Pipeline 我上学时硬件上经常翻译成管线 我觉着更多的是表示**流水线**的概念
* In-Sync Replicas **同步副本** 表示这个副本的复制进度小于配置同步丢失阈值

我看很多文章其实都没有翻译直接用了ISR和Replica，总之您可以先提交PR大家再一起校对。

**Comment by BeanMr** [comment]
这个可以加在前言的部分

**Comment by BeanMr** [comment]
感谢贡献
